import Header from "@/components/Header/Header";
import Providers from "@/components/Provider/Providers";
import type { Metadata } from "next";
import { IBM_Plex_Sans_KR } from "next/font/google";
import "./globals.css";

const IBM = IBM_Plex_Sans_KR({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={IBM.className}>
        <Providers>
          <Header />
          <main className="flex flex-col items-center px-8 md:px-12 min-h-screen bg-[#191B1D] text-white">
            <div className="w-full max-w-[1224px]">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
